@TicketManagerApi_HostAddress = http://localhost:5205/api/
@TicketManager_HostAddress = http://localhost:5205

###
POST {{TicketManager_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "username": "testuser2",
  "email": "testuser2@example.com",
  "password": "TestPassword123!"
}

###
POST {{TicketManager_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin",
  "password": "admin"
}

